import type { AnalysisResult, Suggestion } from "./types";

interface ScoreRating {
  emoji: string;
  label: string;
}

function getScoreRating(score: number): ScoreRating {
  if (score >= 80) return { emoji: "\u{1F7E2}", label: "Excellent" };
  if (score >= 60) return { emoji: "\u{1F535}", label: "Good" };
  if (score >= 40) return { emoji: "\u{1F7E1}", label: "Needs Work" };
  return { emoji: "\u{1F534}", label: "Poor" };
}

function ratingCell(score: number): string {
  const { emoji, label } = getScoreRating(score);
  return `${emoji} ${label}`;
}

function r(value: number): number {
  return Math.round(value);
}

function collectSuggestions(result: AnalysisResult): Suggestion[] {
  const seen = new Set<string>();
  const all: Suggestion[] = [];

  for (const category of [result.aeo, result.seo, result.geo, result.llmo]) {
    for (const s of category.suggestions) {
      if (!seen.has(s.message)) {
        seen.add(s.message);
        all.push(s);
      }
    }
  }

  return all;
}

function renderSuggestionGroup(
  suggestions: Suggestion[],
  type: Suggestion["type"],
  heading: string,
  emptyLabel: string,
): string {
  const filtered = suggestions.filter((s) => s.type === type);
  const lines = [heading];

  if (filtered.length === 0) {
    lines.push(`No ${emptyLabel} issues found.`);
  } else {
    for (const s of filtered) {
      const action = s.action ? ` \u2014 ${s.action}` : "";
      lines.push(`- **${s.message}**${action}`);
    }
  }

  return lines.join("\n");
}

/**
 * Generate a markdown report of analysis results optimized for AI consumption.
 *
 * The report is structured so a user can paste it directly into ChatGPT/Claude
 * and receive actionable fixes for their website.
 *
 * @param result - Full analysis result with AEO/SEO/GEO/LLMO scores
 * @param url - URL of the analyzed page
 * @param timestamp - ISO 8601 timestamp of when analysis was performed
 * @returns Markdown string
 */
export function generateExportMarkdown(
  result: AnalysisResult,
  url: string,
  timestamp: string,
): string {
  const overall = r(result.overall);
  const overallRating = getScoreRating(overall);
  const meta = result.aeo.meta;
  const suggestions = collectSuggestions(result);

  const aeo = result.aeo;
  const seo = result.seo;
  const geo = result.geo;
  const llmo = result.llmo;

  const schemaDisplay = meta?.hasSchema
    ? `\u2705 (${meta.schemaTypes?.length ? meta.schemaTypes.join(", ") : "detected"})`
    : "\u274C None detected";

  const sections: string[] = [
    // Header + AI instruction preamble
    `# Website Optimization Report

> **For AI assistants**: This report was generated by the AEO Score Calculator Chrome extension.
> Analyze the scores and suggestions below, then provide specific, actionable changes
> (code snippets, content rewrites, structural improvements) to improve this page's optimization scores.
> Prioritize critical issues first, then warnings.`,

    // Page Details
    `## Page Details
- **URL**: ${url}
- **Analyzed**: ${timestamp}
- **Overall Score**: ${overall}/100 \u2014 ${overallRating.emoji} ${overallRating.label}`,

    // Score Summary
    `## Score Summary
| Category | Score | Rating |
|----------|-------|--------|
| AEO | ${r(aeo.score)}/100 | ${ratingCell(aeo.score)} |
| SEO | ${r(seo.score)}/100 | ${ratingCell(seo.score)} |
| GEO | ${r(geo.score)}/100 | ${ratingCell(geo.score)} |
| LLMO | ${r(llmo.score)}/100 | ${ratingCell(llmo.score)} |`,

    // AEO Breakdown
    `## AEO Breakdown (Score: ${r(aeo.score)}/100)
| Component | Score | Weight |
|-----------|-------|--------|
| EEAT | ${r(aeo.components.eeat)}/100 | 40% |
| Relevance | ${r(aeo.components.relevance)}/100 | 30% |
| Structure | ${r(aeo.components.structure)}/100 | 20% |
| Freshness | ${r(aeo.components.freshness)}/100 | 10% |
| Tone (LLM) | ${r(aeo.components.tone)}/100 | bonus |
| Uniqueness (LLM) | ${r(aeo.components.uniqueness)}/100 | bonus |`,

    // SEO Breakdown
    `## SEO Breakdown (Score: ${r(seo.score)}/100)
| Component | Score | Weight |
|-----------|-------|--------|
| Technical | ${r(seo.components.technical)}/100 | 30% |
| On-Page | ${r(seo.components.on_page)}/100 | 35% |
| Link Profile | ${r(seo.components.link_profile)}/100 | 20% |
| Image SEO | ${r(seo.components.image_seo)}/100 | 15% |`,

    // GEO Breakdown
    `## GEO Breakdown (Score: ${r(geo.score)}/100)
| Component | Score | Weight |
|-----------|-------|--------|
| Citability | ${r(geo.components.citability)}/100 | 30% |
| Factual Density | ${r(geo.components.factual_density)}/100 | 25% |
| Structured Answers | ${r(geo.components.structured_answers)}/100 | 25% |
| Authority | ${r(geo.components.authority)}/100 | 20% |`,

    // LLMO Breakdown
    `## LLMO Breakdown (Score: ${r(llmo.score)}/100)
| Component | Score | Weight |
|-----------|-------|--------|
| Crawlability | ${r(llmo.components.crawlability)}/100 | 20% |
| Completeness | ${r(llmo.components.completeness)}/100 | 30% |
| Direct Answers | ${r(llmo.components.direct_answers)}/100 | 30% |
| Clarity | ${r(llmo.components.clarity)}/100 | 20% |`,

    // Page Metadata
    `## Page Metadata
- **Word Count**: ${meta?.wordCount ?? 0}
- **Headings**: ${meta?.headingCount ?? 0}
- **Lists**: ${meta?.listCount ?? 0}
- **Tables**: ${meta?.tableCount ?? 0}
- **Images**: ${meta?.imageCount ?? 0}
- **Links**: ${meta?.linkCount ?? 0}
- **Schema Markup**: ${schemaDisplay}
- **FAQ Section**: ${meta?.hasFaq ? "\u2705" : "\u274C"}
- **HowTo Schema**: ${meta?.hasHowto ? "\u2705" : "\u274C"}
- **Snippet Ready**: ${meta?.snippetReady ? "\u2705" : "\u274C"}
- **Last Updated**: ${meta?.lastUpdated ?? "Not detected"}`,

    // Issues & Suggestions
    `## Issues & Suggestions

${renderSuggestionGroup(suggestions, "critical", "### \u{1F534} Critical", "critical")}

${renderSuggestionGroup(suggestions, "warning", "### \u{1F7E1} Warnings", "warning")}

${renderSuggestionGroup(suggestions, "info", "### \u{1F535} Informational", "informational")}`,

    // Footer
    `---
*Generated by [AEO Score Calculator](https://github.com/AEO-Score/aeo-score-calculator) v1.0.0*`,
  ];

  return sections.join("\n\n");
}

/**
 * Generate a filename for the exported markdown report.
 *
 * @param url - URL of the analyzed page
 * @param timestamp - ISO 8601 timestamp
 * @returns Sanitized filename like "aeo-report-example-com-20260402-143000.md"
 */
export function getExportFilename(url: string, timestamp: string): string {
  let hostname = "unknown";
  try {
    hostname = new URL(url).hostname;
  } catch {
    hostname = "unknown";
  }

  const sanitized = hostname.replace(/[^a-zA-Z0-9]/g, "-").replace(/-+/g, "-");

  let datePart = "00000000-000000";
  try {
    const d = new Date(timestamp);
    if (!isNaN(d.getTime())) {
      const pad = (n: number) => String(n).padStart(2, "0");
      datePart = `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;
    }
  } catch {
    /* empty */
  }

  return `aeo-report-${sanitized}-${datePart}.md`;
}
